### ISSUE TITLE
Sticky div in smooth scroll section

### ISSUE THREAD

**Issue by ghost** [grcmichael/gscroll#4]
How can I set a `div` with `position: sticky` that is inside the GScroll section?

**Comment by grcmichael** [comment]
You need to use this example (with the gsap proxy) https://codepen.io/michaelgrc/pen/LYjrzEy and then play with the pin property of ScrollTrigger.

I'm working on some update, and sticky position will works natively.

**Comment by ghost** [comment]
I'll try that! Super excited for the update! Thanks!!

**Comment by ghost** [comment]
Not related to the previous issue (fixed that btw, so thanks again!) but sometimes I'm having a weird issue. Please see the demo video attached. No scroll is happening but the elements jump around.

https://user-images.githubusercontent.com/100540199/158015104-5d6374f7-fc31-457c-bdfc-ebf22c954318.mov

**Comment by ghost** [comment]
The error is quite easy to reproduce: [Codepen](https://codepen.io/kortneykane/pen/VwywPve)

**Comment by grcmichael** [comment]
I think you can fix this issue directly in css: GScroll container must be at least `100vh`

**Comment by ghost** [comment]
@grcmichael With the current setup and utilisations, scrolling does not work on mobile. Do you change body overflow with @media queries or is there another workaround?

**Comment by grcmichael** [comment]
Can you create a new issue please ? It's not related to the initial one. Thank you
